# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'interfaz_caracterizacion.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(801, 642)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(10, 10, 781, 601))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.groupBox = QtWidgets.QGroupBox(self.frame)
        self.groupBox.setGeometry(QtCore.QRect(20, 10, 741, 221))
        self.groupBox.setObjectName("groupBox")
        self.layoutWidget = QtWidgets.QWidget(self.groupBox)
        self.layoutWidget.setGeometry(QtCore.QRect(410, 120, 201, 51))
        self.layoutWidget.setObjectName("layoutWidget")
        self.DetGridLayout = QtWidgets.QGridLayout(self.layoutWidget)
        self.DetGridLayout.setContentsMargins(0, 0, 0, 0)
        self.DetGridLayout.setObjectName("DetGridLayout")
        self.label_7 = QtWidgets.QLabel(self.layoutWidget)
        self.label_7.setObjectName("label_7")
        self.DetGridLayout.addWidget(self.label_7, 0, 0, 1, 1)
        self.HorScaleSpinBox = QtWidgets.QSpinBox(self.layoutWidget)
        self.HorScaleSpinBox.setObjectName("HorScaleSpinBox")
        self.DetGridLayout.addWidget(self.HorScaleSpinBox, 0, 1, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.layoutWidget)
        self.label_8.setObjectName("label_8")
        self.DetGridLayout.addWidget(self.label_8, 1, 0, 1, 1)
        self.VerScaleSpinBox = QtWidgets.QSpinBox(self.layoutWidget)
        self.VerScaleSpinBox.setObjectName("VerScaleSpinBox")
        self.DetGridLayout.addWidget(self.VerScaleSpinBox, 1, 1, 1, 1)
        self.widget = QtWidgets.QWidget(self.groupBox)
        self.widget.setGeometry(QtCore.QRect(40, 120, 201, 81))
        self.widget.setObjectName("widget")
        self.GenGridLayout = QtWidgets.QGridLayout(self.widget)
        self.GenGridLayout.setContentsMargins(0, 0, 0, 0)
        self.GenGridLayout.setObjectName("GenGridLayout")
        self.label_10 = QtWidgets.QLabel(self.widget)
        self.label_10.setObjectName("label_10")
        self.GenGridLayout.addWidget(self.label_10, 0, 0, 1, 1)
        self.WaveFComboBox = QtWidgets.QComboBox(self.widget)
        self.WaveFComboBox.setObjectName("WaveFComboBox")
        self.WaveFComboBox.addItem("")
        self.WaveFComboBox.addItem("")
        self.WaveFComboBox.addItem("")
        self.GenGridLayout.addWidget(self.WaveFComboBox, 0, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.widget)
        self.label_2.setObjectName("label_2")
        self.GenGridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.AmplSpinBox = QtWidgets.QSpinBox(self.widget)
        self.AmplSpinBox.setObjectName("AmplSpinBox")
        self.GenGridLayout.addWidget(self.AmplSpinBox, 1, 1, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.widget)
        self.label_9.setObjectName("label_9")
        self.GenGridLayout.addWidget(self.label_9, 2, 0, 1, 1)
        self.FreqSpinBox = QtWidgets.QSpinBox(self.widget)
        self.FreqSpinBox.setObjectName("FreqSpinBox")
        self.GenGridLayout.addWidget(self.FreqSpinBox, 2, 1, 1, 1)
        self.widget1 = QtWidgets.QWidget(self.groupBox)
        self.widget1.setGeometry(QtCore.QRect(40, 30, 291, 53))
        self.widget1.setObjectName("widget1")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.widget1)
        self.gridLayout_4.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.OpGenPushButton = QtWidgets.QPushButton(self.widget1)
        self.OpGenPushButton.setObjectName("OpGenPushButton")
        self.gridLayout_4.addWidget(self.OpGenPushButton, 0, 0, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label = QtWidgets.QLabel(self.widget1)
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.GIDLineEdit = QtWidgets.QLineEdit(self.widget1)
        self.GIDLineEdit.setPlaceholderText("")
        self.GIDLineEdit.setObjectName("GIDLineEdit")
        self.horizontalLayout_2.addWidget(self.GIDLineEdit)
        self.gridLayout_4.addLayout(self.horizontalLayout_2, 1, 0, 1, 1)
        self.widget2 = QtWidgets.QWidget(self.groupBox)
        self.widget2.setGeometry(QtCore.QRect(410, 30, 291, 53))
        self.widget2.setObjectName("widget2")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.widget2)
        self.gridLayout_5.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.OpDetPushButton = QtWidgets.QPushButton(self.widget2)
        self.OpDetPushButton.setObjectName("OpDetPushButton")
        self.gridLayout_5.addWidget(self.OpDetPushButton, 0, 0, 1, 1)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_6 = QtWidgets.QLabel(self.widget2)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_3.addWidget(self.label_6)
        self.DIDLineEdit = QtWidgets.QLineEdit(self.widget2)
        self.DIDLineEdit.setObjectName("DIDLineEdit")
        self.horizontalLayout_3.addWidget(self.DIDLineEdit)
        self.gridLayout_5.addLayout(self.horizontalLayout_3, 1, 0, 1, 1)
        self.groupBox_2 = QtWidgets.QGroupBox(self.frame)
        self.groupBox_2.setGeometry(QtCore.QRect(20, 240, 741, 341))
        self.groupBox_2.setObjectName("groupBox_2")
        self.MeasurePushButton = QtWidgets.QPushButton(self.groupBox_2)
        self.MeasurePushButton.setGeometry(QtCore.QRect(60, 180, 191, 23))
        self.MeasurePushButton.setObjectName("MeasurePushButton")
        self.layoutWidget1 = QtWidgets.QWidget(self.groupBox_2)
        self.layoutWidget1.setGeometry(QtCore.QRect(60, 60, 191, 81))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.gridLayout = QtWidgets.QGridLayout(self.layoutWidget1)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.label_3 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 0, 0, 1, 1)
        self.MinFreqSpinBox = QtWidgets.QSpinBox(self.layoutWidget1)
        self.MinFreqSpinBox.setObjectName("MinFreqSpinBox")
        self.gridLayout.addWidget(self.MinFreqSpinBox, 0, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 1, 0, 1, 1)
        self.MaxFreqSpinBox = QtWidgets.QSpinBox(self.layoutWidget1)
        self.MaxFreqSpinBox.setObjectName("MaxFreqSpinBox")
        self.gridLayout.addWidget(self.MaxFreqSpinBox, 1, 1, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 2, 0, 1, 1)
        self.NumFreqSpinBox = QtWidgets.QSpinBox(self.layoutWidget1)
        self.NumFreqSpinBox.setObjectName("NumFreqSpinBox")
        self.gridLayout.addWidget(self.NumFreqSpinBox, 2, 1, 1, 1)
        self.SaveImagePushButton = QtWidgets.QPushButton(self.groupBox_2)
        self.SaveImagePushButton.setGeometry(QtCore.QRect(60, 270, 191, 23))
        self.SaveImagePushButton.setObjectName("SaveImagePushButton")
        self.SaveDataPushButton = QtWidgets.QPushButton(self.groupBox_2)
        self.SaveDataPushButton.setGeometry(QtCore.QRect(60, 240, 191, 23))
        self.SaveDataPushButton.setObjectName("SaveDataPushButton")
        self.Axis = MplWidget(self.groupBox_2)
        self.Axis.setGeometry(QtCore.QRect(280, 30, 460, 301))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.Axis.setPalette(palette)
        self.Axis.setObjectName("Axis")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 801, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.groupBox.setTitle(_translate("MainWindow", "Set instruments"))
        self.label_7.setText(_translate("MainWindow", "Horizontal scale"))
        self.label_8.setText(_translate("MainWindow", "Vertical scale"))
        self.label_10.setText(_translate("MainWindow", "Waveform"))
        self.WaveFComboBox.setItemText(0, _translate("MainWindow", "Sinusoidal"))
        self.WaveFComboBox.setItemText(1, _translate("MainWindow", "Squared"))
        self.WaveFComboBox.setItemText(2, _translate("MainWindow", "Pulse"))
        self.label_2.setText(_translate("MainWindow", "Amplitude"))
        self.label_9.setText(_translate("MainWindow", "Frequency"))
        self.OpGenPushButton.setText(_translate("MainWindow", "Open Generator"))
        self.label.setText(_translate("MainWindow", "Generator ID"))
        self.OpDetPushButton.setText(_translate("MainWindow", "Open Detector"))
        self.label_6.setText(_translate("MainWindow", "Detector ID"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Measurement module"))
        self.MeasurePushButton.setText(_translate("MainWindow", "Measure Data"))
        self.label_3.setText(_translate("MainWindow", "Min Frequency"))
        self.label_4.setText(_translate("MainWindow", "Max Frequency"))
        self.label_5.setText(_translate("MainWindow", "# Frequency Values"))
        self.SaveImagePushButton.setText(_translate("MainWindow", "Save Image"))
        self.SaveDataPushButton.setText(_translate("MainWindow", "Save Data"))

from mplwidget import MplWidget

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

